# Generated by Django 3.2.18 on 2023-05-23 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.TextField(blank=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_language', models.CharField(max_length=30)),
                ('original_title', models.TextField()),
                ('overview', models.TextField(blank=True)),
                ('popularity', models.IntegerField()),
                ('poster_path', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('title', models.TextField()),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.IntegerField()),
                ('vote_count', models.IntegerField()),
                ('genre_ids', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
