# Generated by Django 3.2.18 on 2023-05-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowMovie',
            fields=[
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.TextField(blank=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_language', models.CharField(max_length=30)),
                ('original_title', models.TextField()),
                ('overview', models.TextField(blank=True)),
                ('popularity', models.IntegerField()),
                ('poster_path', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('title', models.TextField()),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.IntegerField()),
                ('vote_count', models.IntegerField()),
                ('video_key', models.TextField()),
                ('genre_ids', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
