# Generated by Django 3.2.18 on 2023-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230524_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
    ]
