# Generated by Django 3.2.18 on 2023-05-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20230524_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
